import {StyleSheet} from 'react-native'
export default StyleSheet.create({
    header:{
        width:'100%',
        height:400,
        opacity:0.1
    },
    headerBackground:{
        display:'flex',
        flexDirection:'row',
        backgroundColor:'#d9d9d9'
    },
    image:{
        width:100,
        height:20,
        marginLeft:10,
        marginTop:15
    },
    iconstyle:{
        display:'flex',
        flexDirection:'row',
        marginLeft:220,
        marginTop:5
    },
    container:{
        position:'absolute',
        width:'100%'
    },
    description:{
        marginHorizontal:10
    },
    buynow:{
        fontSize:20,
        marginTop:20,
        color:'#93c22f'
    },
})