import {StyleSheet} from 'react-native'
export default StyleSheet.create({
    header:{
        width:'100%',
        height:400,
        opacity:0.1
    },
    headerBackground:{
        display:'flex',
        flexDirection:'row',
        backgroundColor:'#d9d9d9'
    },
    image:{
        width:100,
        height:20,
        marginLeft:10,
        marginTop:15
    },
    iconstyle:{
        display:'flex',
        flexDirection:'row',
        left:230,
        top:5
    },
    container:{
        position:'absolute',
        top:230,
        left:15
    },
    description:{
        fontSize:23,
        fontWeight:'bold'
    },
    danhmuc:{
        fontSize:18
    },
    buynow:{
        fontSize:20,
        marginTop:20,
        color:'#93c22f'
    },
})