export default {
  SplashScreen: "SplashScreen",
  SignUpScreen: "SignUpScreen",
  SignInScreen: "SignInScreen",
  ForgotPasswordScreen: "ForgotPasswordScreen",
  VerificationCodeScreen: "VerificationCodeScreen",
  OnboardingScreen: "OnboardingScreen",
  Browse02Screen: "Tìm kiếm",
  OrdersScreen: "Đặt hàng",
  FavoritesScreen: "Yêu thích",
  NotificationsScreen: "Thông báo",
  AccountScreen: "Tài khoản",
  HomeBottomTab: "HomeBottomTab",
  Browse01Screen: "Browse01Screen",
  Browse03Screen: "Browse03Screen",
  CheckoutScreen: "CheckoutScreen",
  PaymentScreen: "PaymentScreen",
  ProductDetailScreen: "ProductDetailScreen",
  SearchScreen: "SearchScreen",
  SetLanguageScreen: "SetLanguageScreen",
  SettingScreen: "SettingScreen",
  ShoppingCartScreen: "ShoppingCartScreen",
  SuccessScreen: "SuccessScreen",
  Categories01Screen: "Categories01Screen",
  Categories02Screen: "Categories02Screen",
  FilterScreen: "FilterScreen",
  OrdersDeliveryScreen: "OrdersDeliveryScreen",
  OrdersPickupsScreen: "OrdersPickupsScreen",
  Loading: "Loading",
  Home: "Home",
  Authentication: "Auth",
}
